const fs = require('fs');
const path = require('path');
let content = fs.readFileSync(path.join('C:\\Users\\Admin\\Documents\\New project', 'index.html'), 'utf8');

// INSERT function for features that have NO fd-qa div at all
function insertQA(featureId, qaHtml) {
    const featureStart = content.indexOf(`'${featureId}':`);
    if (featureStart === -1) { console.log(`MISS feature: ${featureId}`); return; }
    // Find the closing backtick+comma that ends the template literal for this feature
    // Pattern: </div>`, (closing last div then backtick then comma)
    const endPattern = '</div>`,';
    const endPos = content.indexOf(endPattern, featureStart);
    if (endPos === -1) { console.log(`MISS end: ${featureId}`); return; }
    // Insert FAQ right before the backtick (after </div>)
    const insertAt = endPos + '</div>'.length;
    const faqSection = '\n<h4>❓ Giải đáp thắc mắc thường gặp</h4>\n' + qaHtml;
    content = content.slice(0, insertAt) + faqSection + content.slice(insertAt);
    console.log(`OK inserted: ${featureId}`);
}

insertQA('fd-cci', `<div class="fd-qa">
<p class="fd-q">❓ CCI (Cardiac Conductance Index) đo "sức khỏe mạch máu" theo cơ chế vật lý nào?</p>
<p class="fd-a">✅ CCI không phải điện tim — là phân tích cơ học mạch máu từ sóng PPG. Mỗi nhịp tim tống máu → sóng áp lực lan truyền qua động mạch với tốc độ phụ thuộc vào độ cứng mạch (Moens-Korteweg equation: PWV = √(Eh/ρr), trong đó E = Young's modulus của thành mạch). HeartSense extract từ PPG: (1) Pulse Transit Time (PTT) → proxy cho PWV → tính ASI; (2) Beat-to-beat amplitude variation → Pulse Amplitude Variability (PAV); (3) Area under diastolic curve → Hemodynamic Capacitance (HC). Ba chỉ số này mô tả đặc tính cơ học của hệ mạch toàn thân.</p>
<p class="fd-q">❓ Arterial Stiffness Index (ASI) trong CCI khác với chỉ số PWV đo bằng thiết bị y tế như thế nào?</p>
<p class="fd-a">✅ Gold standard PWV: đo bằng Complior hoặc SphygmoCor — đặt cảm biến tại carotid và femoral arteries, đo delay của pulse wave giữa 2 điểm → carotid-femoral PWV (cfPWV). Reference value bình thường: cfPWV &lt;10 m/s. HeartSense ASI: proxy từ PTT (finger PPG) và diastolic waveform morphology — đo tại peripheral bed (ngón tay), không tại aorta. Correlation với cfPWV: r=0.72–0.78 trong published studies. Không calibrated theo absolute m/s vì measurement site khác nhau. Useful cho TREND monitoring (tăng hay giảm) không phải absolute cardiovascular risk staging. Người cần absolute PWV cho risk stratification cần clinical measurement.</p>
<p class="fd-q">❓ Tại sao đo 2 tay (trái và phải) để phát hiện hẹp mạch một bên?</p>
<p class="fd-a">✅ Inter-arm ASI difference (IAD): động mạch dưới đòn trái và phải cấp máu cho 2 tay. Hẹp một bên (subclavian stenosis, thoracic outlet syndrome, peripheral artery disease) → PPG amplitude giảm, PTT dài hơn phía hẹp. IAD &gt;15% → gợi ý bất đối xứng mạch đáng kể. Subclavian steal syndrome: hẹp subclavian proximal → máu "đánh cắp" từ tuần hoàn não qua vertebral artery → nguy cơ đột quỵ. Inter-arm blood pressure difference (IABD) &gt;10–15 mmHg là marker established cho cardiovascular risk (ABI, LEAD). CCI 2 tay = non-invasive screening tool cho vascular asymmetry — cần confirm với Doppler ultrasound nếu IAD cao.</p>
<p class="fd-q">❓ Hemodynamic Capacitance (HC) thấp có ý nghĩa lâm sàng gì?</p>
<p class="fd-a">✅ HC = khả năng "buffer" của hệ mạch: mạch đàn hồi tốt → hấp thụ xung áp từ systole → HA diastolic duy trì ổn định. HC thấp → mạch cứng → pulse pressure cao (SBP - DBP rộng hơn bình thường) → isolated systolic hypertension → tăng tải trên tim trái. Lâm sàng: HC thấp ở người &gt;60 tuổi là independent predictor of cardiovascular events (Safar et al. JACC 2003). HC giảm theo aging là normal nhưng giảm nhanh hơn expected → accelerated vascular aging → investigate risk factors (smoking, diabetes, dyslipidemia). HeartSense track HC trend theo thời gian — nếu giảm đột ngột không có aging reason → alert.</p>
<p class="fd-q">❓ Người với AFib, CCI có bị nhiễu vì nhịp không đều không?</p>
<p class="fd-a">✅ AFib ảnh hưởng CCI: beat-to-beat RR variation trong AFib làm filling volume khác nhau → stroke volume khác nhau → pulse amplitude khác nhau. PAV trong AFib naturally cao — không phải vascular pathology mà là mechanical consequence của irregular rhythm. HeartSense AFib-aware CCI: khi AFib detected → PAV excluded từ CCI composite (tránh false flag "mạch không ổn định" khi chỉ là AFib mechanical effect); chỉ ASI và HC được report trong AFib session. ASI và HC: vẫn reliable trong AFib nếu dùng median hay trimmed mean (resistant to outliers). CCI đáng tin nhất trong NSR — in AFib, interpret with awareness of rhythm context.</p>
<p class="fd-q">❓ CCI thay đổi nhanh không khi điều trị (thuốc hoặc thay đổi lối sống)?</p>
<p class="fd-a">✅ Timeline thay đổi CCI theo intervention: Acute (phút-giờ): nitroglycerin (vasodilator) → ASI giảm ngay; exercise-induced endothelial dilation → ASI giảm ngay sau tập. Short-term (ngày-tuần): kiểm soát THA tốt → ASI giảm 5–10% trong 2–4 tuần; giảm natri ăn → HC cải thiện trong 1–2 tuần; ngừng hút thuốc → endothelial function bắt đầu phục hồi sau 2–4 tuần. Long-term (tháng): weight loss, aerobic exercise, statin therapy → ASI giảm có thể thấy trong 3–6 tháng. CCI là endpoint nhạy hơn lâm sàng event (không cần chờ heart attack để thấy benefit of treatment).</p>
<p class="fd-q">❓ Người trẻ (dưới 30 tuổi) với CCI bất thường — nên lo lắng đến mức nào?</p>
<p class="fd-a">✅ Người trẻ &lt;30 tuổi với ASI cao (unexpected arterial stiffness) cần investigate: (1) Familial hypercholesterolemia — LDL rất cao từ nhỏ → vascular remodeling sớm; (2) Chronic kidney disease (CKD) — accelerated vascular calcification; (3) Marfan/Ehlers-Danlos syndrome — connective tissue disorder ảnh hưởng arterial wall properties; (4) Chronic use of NSAIDs, corticosteroids; (5) Autoimmune (lupus, rheumatoid arthritis) — systemic inflammation accelerating vascular aging. Không panic từ 1 high reading — CCI có intra-session variability. Consistent high ASI across 3–5 sessions: discuss với bác sĩ về workup. HeartSense flag: "ASI cao hơn expected cho độ tuổi — xem xét khám tim mạch nếu tái diễn."</p>
</div>`);

insertQA('fd-safe-exercise', `<div class="fd-qa">
<p class="fd-q">❓ Tại sao HRV quyết định "liều vận động an toàn" tốt hơn cảm giác chủ quan?</p>
<p class="fd-a">✅ HRV phản ánh trạng thái hệ thần kinh tự chủ (ANS) — mà người tập không thể tự đánh giá chính xác bằng cảm giác. Intra-day HRV variation: sáng dậy HRV thấp (cơ thể chưa phục hồi hoàn toàn) vs. chiều HRV cao hơn. Ngày bệnh nhẹ hoặc stress cao: HRV thấp nhưng người cảm thấy "tạm ổn" — tập nặng sẽ làm tệ hơn. Overtraining syndrome: HRV giảm dần nhiều ngày liên tiếp trước khi người tập "cảm thấy overtrained". HRV-guided training (Buchheit & Laursen 2013): improve performance 15% so với fixed schedule — bằng cách tập đúng cường độ đúng ngày thay vì tập đều đặn bất kể trạng thái ANS.</p>
<p class="fd-q">❓ Cơ chế nào giải thích tại sao tập nặng khi HRV thấp có thể trigger AFib?</p>
<p class="fd-a">✅ Multi-pathway mechanism: (1) Sympathetic surge: tập nặng → catecholamine release → atrial trigger (adrenergic AFib trigger pathway); (2) Vagal withdrawal: exercise abruptly stops residual vagal tone → ANS imbalance → atrial vulnerability; (3) HRV thấp baseline → sympathetic dominant → lower trigger threshold. Athlete's heart paradox: endurance athletes có vagal tone rất cao → paradoxical vagal triggers post-exercise. "Lone AFib" trong young athletes: post-exercise AFib xảy ra khi HR bắt đầu giảm — vagal rebound sau sympathetic surge. Người có AFib substrate thêm stress exercise trong ngày ANS đã bất ổn = stacked risk. Safe exercise guideline dựa trên nguyên lý: không add catecholamine load khi substrate đã vulnerable.</p>
<p class="fd-q">❓ Ngưỡng BPM nào trong khi tập là an toàn cho người có AFib?</p>
<p class="fd-a">✅ Heart Rate targets trong exercise cho AFib: Moderate exercise (generally safe): 50–70% maximum HR (220-tuổi). Ví dụ: 60 tuổi → max HR ~160 → target zone 80–112 bpm. Vigorous exercise (cần clearance bác sĩ): 70–85% max HR. Avoid: &gt;85% max HR nếu AFib burden &gt;10% hoặc uncontrolled AFib. Đặc biệt với rate control drugs: beta-blocker/CCB limit max HR response → người dùng metoprolol đừng dùng percentage-based targets (HR không reach predicted max) — dùng RPE (Rate of Perceived Exertion, Borg scale 12–14 "somewhat hard"). HeartSense Exercise Monitor: alert nếu HR trong session vượt personal threshold, không dùng population target chung.</p>
<p class="fd-q">❓ Post-AFib episode bao lâu thì có thể tập lại?</p>
<p class="fd-a">✅ Post-episode return to exercise protocol: Immediate (0–24h sau episode): nghỉ hoàn toàn — không tập ngay cả nhẹ; đảm bảo rhythm đã return to baseline. 24–48h sau: đo HeartSense — nếu AFib Index &lt;10% và Recovery Score &gt;40 → có thể đi bộ nhẹ 10–15 phút. 48–72h: nếu ổn định → light aerobic (walking, gentle cycling) 20 phút ở 50–60% max HR. Tuần 1 post-episode: không vigorous exercise; monitor daily với HeartSense. Return to pre-episode level: sau 7–10 ngày không có new episode. Nếu episodes frequent (&gt;2/tháng): discuss với bác sĩ về supervised cardiac rehabilitation program thay vì self-managed exercise.</p>
<p class="fd-q">❓ Những môn thể thao nào tốt nhất và tệ nhất cho người AFib?</p>
<p class="fd-a">✅ Best cho AFib: walking (đi bộ nhanh) — steady moderate intensity, easy to modulate; swimming (bơi) — horizontal position giảm cardiac preload, buoyancy giảm musculoskeletal load, cooling reduces catecholamine; cycling (đạp xe) — non-impact, easy to control intensity; yoga/tai chi — mind-body, parasympathetic activation, đặc biệt tốt cho vagal tone. Worst cho AFib: heavy weight lifting — Valsalva maneuver tạo huge vagal-then-sympathetic swing, AFib trigger; competitive sports with sudden intensity changes; extreme endurance (marathon) — accumulated catecholamine over hours; contact sports (boxing) — chest trauma. Moderate aerobic 30–45 phút, 5 ngày/tuần giảm AFib burden 18–25% theo systematic review (La Gerche 2013).</p>
<p class="fd-q">❓ Cardiac rehabilitation (phục hồi tim mạch) có khác gì với tự tập theo HeartSense?</p>
<p class="fd-a">✅ Cardiac rehabilitation (CR) supervised: có y tá hoặc physiotherapist giám sát; ECG monitor realtime trong session; máy khử rung sẵn sàng; protocol evidence-based; suitable cho: post-MI, post-CABG, post-ablation, heart failure, severe AFib. HeartSense self-guided: phù hợp cho paroxysmal AFib ổn định, HRV-guided daily decision, track progress dài hạn, motivation và adherence. Kết hợp tốt nhất: hoàn thành CR program (8–12 tuần) → dùng HeartSense cho long-term self-managed exercise monitoring sau CR. HeartSense không phải substitute cho CR trong những trường hợp indication CR (recent hospitalization, complex AFib, EF thấp). Biết khi nào mình cần supervised care là part of safe exercise judgment.</p>
<p class="fd-q">❓ Thời điểm tốt nhất trong ngày để tập cho người AFib?</p>
<p class="fd-a">✅ Chronobiology và AFib timing: AFib episodes xảy ra thường xuyên hơn vào sáng sớm (6–10h) — sympathetic surge khi thức dậy (cortisol peak, catecholamine surge, platelet aggregability cao). Implication: tránh vigorous exercise trong 1h đầu sau thức dậy — sympathetic tone đã cao, thêm exercise load = stacked trigger risk. Tốt nhất: late morning (10–12h) hoặc early afternoon (14–16h) — cortisol đã giảm từ peak sáng, không quá gần giờ ngủ. Tránh: vigorous exercise trong 2–3h trước ngủ — catecholamine từ exercise ảnh hưởng sleep onset và HRV đêm. HeartSense Circadian Safety: kết hợp daily rhythm analysis với exercise timing recommendation cá nhân hóa.</p>
</div>`);

insertQA('fd-med-effectiveness', `<div class="fd-qa">
<p class="fd-q">❓ Làm thế nào HeartSense biết thuốc đang "có hiệu quả" — cơ sở khoa học nào?</p>
<p class="fd-a">✅ Drug effectiveness inference từ biomarker response: mỗi loại thuốc tim mạch có expected pharmacodynamic signature trong HeartSense metrics. Beta-blocker (metoprolol, bisoprolol): cơ chế beta-1 receptor blockade → giảm chronotropy và inotropy → BPM nghỉ giảm 10–20 bpm. Nếu BPM không giảm sau 2 tuần adequate dose → poor compliance OR poor absorption OR high sympathetic tone override. Antiarrhythmic (Flecainide): sodium channel block → reduce ectopic trigger excitability → AFib Burden giảm. NOAC: không có direct PPG metric để track anticoagulant effect — tracking Clot-Risk Score change as surrogate. Drug response heterogeneity: genetic polymorphism trong CYP2D6 ảnh hưởng metoprolol metabolism — người poor metabolizer có higher drug levels với same dose.</p>
<p class="fd-q">❓ Nếu thuốc "không hiệu quả" theo HeartSense, có phải tự ngừng thuốc không?</p>
<p class="fd-a">✅ Tuyệt đối không — HeartSense "không hiệu quả" = data point để thảo luận với bác sĩ, không phải chỉ dẫn tự ngừng. Ngừng thuốc tự ý nguy hiểm: antiarrhythmic agents — rebound arrhythmia nếu ngừng đột ngột; beta-blocker — rebound tachycardia và hypertension nếu stop abruptly sau dùng dài ngày (upregulation beta-receptors); NOAC — thromboembolic event risk tăng đột ngột nếu ngừng. Khi HeartSense flag "hiệu quả thấp hơn kỳ vọng" → đặt lịch gặp bác sĩ sớm (không khẩn cấp trừ symptoms tệ hơn) → bác sĩ quyết định: tăng liều, đổi thuốc, hoặc investigate non-compliance. Luôn tiếp tục thuốc trong khi chờ appointment.</p>
<p class="fd-q">❓ Có trường hợp thuốc "hoạt động" nhưng HeartSense nói "không hiệu quả" không?</p>
<p class="fd-a">✅ False negatives có thể xảy ra: (1) Baseline không được establish đúng: nếu người dùng bắt đầu thuốc ngay hôm đầu cài app, không có pre-drug baseline → không thể compare; (2) Confounding lifestyle changes: cùng lúc bắt đầu thuốc, người dùng cũng bắt đầu giảm rượu → cả hai làm HRV tăng nhưng app attribute sai (hoặc đúng?); (3) Indirect drugs: NOAC không có PPG signature → luôn "unclear effectiveness" trong HeartSense (cần INR/anti-Xa để verify); (4) Drugs that work via non-HRV pathways: statins, ACE inhibitors có benefit vascular nhưng không affect BPM/HRV directly trong short-term. System thông báo rõ: "Evaluation chỉ dựa trên BPM, HRV, và AFib Burden — không phải toàn bộ therapeutic effects của thuốc."</p>
<p class="fd-q">❓ Đánh giá hiệu quả thuốc với NOAC (xiquellis, eliquis, pradaxa) như thế nào?</p>
<p class="fd-a">✅ NOACs không có direct HeartSense metric để track. Anticoagulant effect (anti-Xa hay anti-IIa) không ảnh hưởng HRV, BPM, hay PPG waveform. Indirect proxy tracking: Clot-Risk Score change (bao gồm AFib Burden, HR, activity level) — nếu Clot-Risk giảm sau bắt đầu NOAC, nhưng đây là từ rhythm control, không từ anticoagulation directly. HeartSense NOAC evaluation: chỉ track adherence (có log uống thuốc mỗi ngày không), không track effectiveness. Medication adherence cực quan trọng với NOAC (ngắn half-life — bỏ 1–2 liều = anticoagulation gap = stroke risk). Real NOAC monitoring: nếu dùng Warfarin, cần INR check định kỳ. NOAC: không cần routine monitoring nhưng bác sĩ có thể order anti-Xa level khi cần (obesity, CKD, bleeding).</p>
<p class="fd-q">❓ Biên độ thay đổi tối thiểu (minimal clinically important difference) là bao nhiêu để tin rằng thuốc thực sự có hiệu quả?</p>
<p class="fd-a">✅ MCID (Minimal Clinically Important Difference) cho HeartSense metrics: BPM: ±5 bpm (systematic change, not noise); RMSSD: ±5ms; AFib Burden: ±5% absolute (từ 20% xuống 15% = meaningful). Statistical threshold trong HeartSense: dùng paired t-test (pre vs. post) với p&lt;0.05 VÀ effect size Cohen's d &gt;0.3 để classify "effective". Noise level estimation: intra-week BPM variability ±3–4 bpm → need &gt;5 bpm change để signal above noise. Time needed for stable measurement: minimum 2 tuần pre-drug baseline (≥10 sessions) và 2 tuần post-drug (≥10 sessions) để có meaningful comparison. Less than 10 sessions per period: confidence interval too wide → inconclusive, not "ineffective."</p>
<p class="fd-q">❓ HeartSense có thể phát hiện side effects của thuốc tim mạch không?</p>
<p class="fd-a">✅ Side effect detection via metrics: Bradycardia (beta-blocker overdose): BPM resting &lt;50 bpm + HRR impaired + fatigue log → flag. AV block (từ beta-blocker, digoxin, CCB cao): rhythm irregularity pattern khác AFib → flag "unusual rhythm, not AFib pattern — review medications." QT prolongation (sotalol, amiodarone): không trực tiếp measurable từ PPG (cần ECG); indirect: nếu VT/torsades → người dùng log syncope/palpitations + HeartSense thấy sudden HR changes. Proarrhythmic effect (flecainide causing atrial flutter): flutter có pattern khác AFib trong synthetic ECG — detectable. Không thể detect: dry cough từ ACE inhibitor (không cardiac); hepatotoxicity từ amiodarone (cần liver function tests). HeartSense "Drug Side Effect" log: người dùng log symptoms → HeartSense correlate với medication timeline và metrics.</p>
<p class="fd-q">❓ Nếu bác sĩ thay đổi thuốc, cần làm gì trong HeartSense?</p>
<p class="fd-a">✅ Medication change workflow: (1) Ngay khi nhận đơn thuốc mới: cập nhật Pill Pocket — add thuốc mới, mark ngày ngừng thuốc cũ; (2) HeartSense auto-create "medication change event" trên timeline — anchor point cho effectiveness tracking; (3) New effectiveness baseline period: 7 ngày washout (nếu đổi từ thuốc này sang thuốc khác cùng class) hoặc 0 ngày (nếu add-on); (4) Effectiveness tracking start: 2 tuần sau ngày bắt đầu thuốc mới; (5) Drug interaction check: ngay khi add thuốc mới, HeartSense check với list thuốc đang dùng và flag nếu có significant interaction. Doctor Export sau 4 tuần dùng thuốc mới: tự động include "Effectiveness Report" so sánh metrics trước và sau medication change — data bác sĩ cần tại follow-up appointment.</p>
</div>`);

insertQA('fd-keyboard-bcg', `<div class="fd-qa">
<p class="fd-q">❓ Keyboard BCG đo nhịp tim từ bàn phím máy tính theo cơ chế Newton III nào?</p>
<p class="fd-a">✅ Ballistocardiography (BCG) qua bàn phím: mỗi lần tim co bóp → blood ejection tạo reactive force (Newton III: mỗi action có equal and opposite reaction) → body dịch chuyển nhỏ → ngón tay trên keyboard chịu micro-force variations → pressure sensor hoặc accelerometer trong keyboard detect. Laptop keyboard với built-in capacitive pressure sensors (nhiều MacBook, ThinkPad) có thể detect cardiac pulse đủ để analyze. Signal: ~5–20 mN force variation per heartbeat ở ngón tay đặt yên trên keyboard. Not applicable nếu đang gõ phím — chỉ khi đặt yên ngón tay trên keys.</p>
<p class="fd-q">❓ Những loại bàn phím nào tương thích và loại nào không?</p>
<p class="fd-a">✅ Tương thích: laptop keyboards với force touch (MacBook 2015+ butterfly/scissor + force touch trackpad — trackpad tốt hơn keyboard cho BCG); ThinkPad với TrackPoint (pressure sensor sensitivity tốt); một số mechanical keyboards với strain gauge integration (Topre switches có capacitive sensing). Không tương thích: membrane keyboards phổ thông (quá stiff, không sensitive); wireless keyboards (không có direct connection để read sensor data); gaming keyboards thông thường. Trackpad BCG tốt hơn keyboard BCG: trackpad pressure sensors nhạy hơn và designed cho light touch → cardiac pulse detection tốt hơn.</p>
<p class="fd-q">❓ Có cần phần mềm đặc biệt hay driver để đọc keyboard sensor data không?</p>
<p class="fd-a">✅ Platform-specific implementation: macOS: Force Touch trackpad data accessible qua NSTouch API — HeartSense macOS app có native implementation. Windows: không có standard API cho pressure data từ laptop touchpad — vendor-specific (Synaptics SDK, Elan SDK) với varying availability. Linux: evdev input subsystem có some pressure data nhưng limited. Web app JavaScript: không có access đến hardware pressure sensors via standard browser APIs — keyboard BCG cần native app, không thể làm web-based. External BCG devices: một số research groups built dedicated BCG sensor pads (force plate) — more reliable nhưng không built-in.</p>
<p class="fd-q">❓ Tại sao cần ngồi yên và không gõ phím trong phiên đo BCG keyboard?</p>
<p class="fd-a">✅ Signal amplitude comparison: cardiac BCG signal ở ngón tay ~5–20 mN; keystroke impact ~200–500 mN (10–100× lớn hơn). Gõ phím trong lúc đo: keystroke artifacts overwhelm cardiac signal hoàn toàn — không thể extract. Phương án đo: đặt fingertips nhẹ lên keyboard (không nhấn) trong 60 giây → cardiac pulse in resting fingers → BCG signal. Resting fingertip pressure optimal: 5–10 grams (light touch). Breathing artifacts: chuyển động ngực từ thở tạo low-frequency artifact (0.2–0.4 Hz) → filtered ra trước cardiac analysis.</p>
<p class="fd-q">❓ Keyboard BCG có thể detect AFib không?</p>
<p class="fd-a">✅ Feasibility stage: BCG waveform capture beat-to-beat timing → RR interval analysis → irregularity detection → possible AFib flag. Accuracy kém hơn optical PPG: BCG signal weaker, more susceptible to environmental vibration. Published keyboard BCG studies (Tarvainen et al., Gordon et al.): HR accuracy ±5 bpm, HRV correlation r=0.7 với ECG reference — acceptable cho screening, không cho clinical decision. AFib detection ~75% sensitivity — không đủ cao cho standalone AFib screening. Keyboard BCG best use: continuous passive monitoring trend kết hợp với periodic active measurement (finger PPG) để confirm.</p>
<p class="fd-q">❓ Tư thế ngồi ảnh hưởng đến kết quả BCG bàn phím như thế nào?</p>
<p class="fd-a">✅ Biomechanics: tim co bóp → thân mình → cánh tay → ngón tay → keyboard. Signal attenuates tại mỗi joint. Tư thế tốt: cánh tay duỗi thẳng đặt lên keyboard (typical typing posture) → signal path ngắn, ít attenuation. Cánh tay gập nhiều (keyboard quá cao): extra joint angle → more attenuation. Chair vibration: ghế trên xe/bus → add noise. Khuỷu tay đặt trên bàn: ground chair vibration → tốt hơn. Optimal: ngồi thẳng, khuỷu tay ~90°, cổ tay thư giãn trên keyboard.</p>
<p class="fd-q">❓ HeartSense có thể monitor liên tục passive BCG trong khi làm việc không?</p>
<p class="fd-a">✅ Passive continuous BCG là primary value proposition: app chạy background, periodically (mỗi 15 phút) lấy 30 giây "idle window" khi người dùng không gõ phím → analyze BCG → update daily trend. Không interrupt workflow — người dùng không cần làm gì. Idle detection: HeartSense detect khi không có keystroke trong 30 giây → silently analyze BCG. Kết quả: "Trong 4 giờ làm việc hôm nay, 12 BCG samples: BPM average 72, HRV trend stable, no irregularity detected." Office worker use case: full-day passive monitoring không cần active session — complementary với morning active finger PPG measurement.</p>
</div>`);

fs.writeFileSync(path.join('C:\\Users\\Admin\\Documents\\New project', 'index.html'), content, 'utf8');
console.log('INSERT done — fd-cci, fd-safe-exercise, fd-med-effectiveness, fd-keyboard-bcg!');
